services:
  - type: web
    name: goorm-kakao-login
    env: java
    buildCommand: "./gradlew build"
    startCommand: "java -jar build/libs/Kakao_Login-0.0.1-SNAPSHOT.jar"
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
